---
- name: synchronize consul-alerts repo
  git:
    repo: "https://github.com/AcalephStorage/consul-alerts.git"
    dest: "/usr/local/go/src/github.com/AcalephStorage/consul-alerts"
    version: "{{ consulAlerts_version }}"
    update: true
  register: newRelease

- name: build and install consul-alerts
  shell: "cd /usr/local/go/src/github.com/AcalephStorage/consul-alerts && go get && go install"
  when: newRelease.changed or consulAlerts_reinstall is defined

- name: ensure executable files
  file:
    path: "/usr/local/go/bin/consul-alerts"
    owner: root
    mode: "0755"
